displayName=Nice day for fushin', ain't it?
author=peepoBlush
description=Plays sound clip from legendary NPC Baelin everytime you start fishing
tags=fishing,sound
version=
plugins=org.fushin.FishingSoundPlugin
build=standard
