displayName=Nice day for fushin', ain't it?
author=peepoBlush
description=Plays sound clip from legendary NPC Baelin everytime you start fishing
tags=
version=
plugins=org.fushin.PluginLauncher
build=standard